// web/app/offers/page.tsx
import {
  GetOffersDocument,
  GetOffersQuery,
} from "@/graphql/__generated__/graphql";
import { getClient } from "@/lib/apollo";
import {
  Card,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import Image from "next/image";
import { Badge } from "@/components/ui/badge";
import { userSession } from "@/lib/session";

export default async function Offers() {
  await userSession();
  const { data } = await getClient().query<GetOffersQuery>({
    query: GetOffersDocument,
  });

  return (
    <div className="grid grid-flow-row gap-4">
      {data.offers.map(({ shortName, name, count, id, imageUrl }) => (
        <Card key={id}>
          <div className="grid grid-flow-col justify-between">
            <CardHeader className="grid justify-between">
              <CardTitle>{shortName}</CardTitle>
              <CardDescription>{name}</CardDescription>
              <Badge className="w-fit h-fit">{count} available</Badge>
            </CardHeader>
            <CardHeader>
              <Image src={imageUrl} alt={shortName} width={100} height={100} />
            </CardHeader>
          </div>
          {/* <CardFooter>
            <Skeleton className="h-2 w-full bg-primary/50" />
          </CardFooter> */}
        </Card>
      ))}
    </div>
  );
}

// web/src/lib/components/tabs/offers.svelte
<script lang="ts">
	import * as Card from '$lib/components/ui/card';
	import { Badge } from '$lib/components/ui/badge';
	import { Skeleton } from '$lib/components/ui/skeleton';
	import { writable, type Writable } from 'svelte/store';
	import DealCode from '../deal-code.svelte';
	import { slide } from 'svelte/transition';

	export let offersList: Promise<import('$houdini').Index$result['offers'] | undefined>;
	let state: Writable<Record<number, Array<{ id: string }>>> = writable({});

	const addOffer = (offerId: number, id: string) => {
		// FIXME: :)
		if (!$state[offerId]) {
			$state[offerId] = [];
		}

		$state[offerId].push({ id });

		$state = $state;
	};

	const removeOffer = async (offerId: number, id: string) => {
		state.update((s) => ({ ...s, [offerId]: s[offerId].filter((o) => o.id !== id) }));
	};
</script>

<div class="grid grid-flow-row gap-4">
	{#await offersList}
		{#each Array(30) as _}
			<Card.Root>
				<div class="flex">
					<Card.Header class="flex flex-grow flex-col">
						<Skeleton class="h-[22px] w-[20%] rounded-xl" />
						<Skeleton class="h-[26px] w-[50%] rounded-xl" />
						<Skeleton class="h-[24px] w-[7%] rounded-xl" />
					</Card.Header>
					<Card.Header>
						<Skeleton class="h-[90px] w-[90px] rounded-xl" />
					</Card.Header>
				</div>
			</Card.Root>
		{/each}
	{:then offersList}
		{#each offersList ?? [] as { shortName, name, count, imageBasename, offerPropositionId }}
			<Card.Root
				on:click={() => {
					if (($state[offerPropositionId]?.length ?? 0) < count) {
						addOffer(offerPropositionId, crypto.randomUUID());
					}
				}}
			>
				<div class="grid grid-flow-col justify-between">
					<Card.Header class="grid justify-between">
						<Card.Title>{shortName}</Card.Title>
						<Card.Description>{name}</Card.Description>
						<Badge class="h-fit w-fit">{count} available</Badge>
					</Card.Header>
					<Card.Header>
						<img
							class="rounded-xl"
							src={`api/images/${imageBasename}`}
							alt={shortName}
							width={90}
							height={90}
						/>
					</Card.Header>
				</div>
				{#if $state[offerPropositionId] && $state[offerPropositionId].length > 0}
					<Card.Footer>
						<div in:slide out:slide class="grid h-full w-full grid-flow-row gap-2">
							{#each $state[offerPropositionId] as { id }}
								<span in:slide out:slide>
									<DealCode
										offerId={offerPropositionId}
										{id}
										removeSelf={() => removeOffer(offerPropositionId, id)}
									/>
								</span>
							{/each}
						</div>
					</Card.Footer>
				{/if}
			</Card.Root>
		{/each}
	{/await}
</div>
