// web/src/routes/login/+page.svelte
<script lang="ts">
	import type { ActionData } from './$types';
	import { enhance } from '$app/forms';
	import { ExclamationTriangle } from 'radix-icons-svelte';
	import * as Card from '$lib/components/ui/card';
	import { Label } from '$lib/components/ui/label';
	import { Input } from '$lib/components/ui/input';
	import { Button } from '$lib/components/ui/button';
	import * as Alert from '$lib/components/ui/alert';

	export let form: ActionData;
</script>

<svelte:head>
	<title>Login | Maccas</title>
</svelte:head>

<Card.Root>
	<Card.Header>
		<Card.Title>Login</Card.Title>
	</Card.Header>
	<form method="POST" use:enhance>
		<Card.Content>
			<div class="grid w-full items-center gap-4">
				<Label for="username">Username</Label>
				<Input id="username" type="username" placeholder="Username" name="username" />
				<Label for="password">Password</Label>
				<Input id="password" type="password" placeholder="Password" name="password" />
			</div>
		</Card.Content>
		<Card.Footer class="w-full">
			<div class="w-full">
				{#if form?.error}
					<div class="mb-4 w-full">
						<Alert.Root variant="destructive">
							<ExclamationTriangle class="h-4 w-4" />
							<Alert.Title>Error</Alert.Title>
							<Alert.Description>{form.error}</Alert.Description>
						</Alert.Root>
					</div>
				{/if}

				<Button type="submit">Login</Button>
			</div>
		</Card.Footer>
	</form>
</Card.Root>

// web/app/auth/login/page.tsx
"use client";

import { Input } from "@/components/ui/input";
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { LoginState, login } from "@/app/actions/login";
import { useFormState } from "react-dom";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { ExclamationTriangleIcon } from "@radix-ui/react-icons";
import SubmitButton from "@/components/submit-button";

export default function Login() {
  const [state, formAction] = useFormState<LoginState, FormData>(login, {
    error: null,
  });

  return (
    <Card>
      <CardHeader>
        <CardTitle>Login</CardTitle>
      </CardHeader>
      <form action={formAction}>
        <CardContent>
          <div className="grid w-full items-center gap-4">
            <Label htmlFor="username">Username</Label>
            <Input
              id="username"
              type="username"
              placeholder="Username"
              name="username"
            />
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              type="password"
              placeholder="Password"
              name="password"
            />
          </div>
        </CardContent>
        <CardFooter className="w-full">
          <div className="w-full">
            {state.error && (
              <div className="mb-4 w-full">
                <Alert variant="destructive">
                  <ExclamationTriangleIcon className="h-4 w-4" />
                  <AlertTitle>Error</AlertTitle>
                  <AlertDescription>{state.error}</AlertDescription>
                </Alert>
              </div>
            )}
            <SubmitButton>Login</SubmitButton>
          </div>
        </CardFooter>
      </form>
    </Card>
  );
}
